### PR TITLE
Fix #200 - Allow syncing developer settings in DeveloperSettingsPresenter

### LINKED ISSUE #200: Syncing developer settings in between activities
Say there are two activities, `A` and `B`, which both have a `ViewModifier` that inserts a `DeveloperSettingsFragment` inside a `FrameLayout`.
1. Navigate from activty `A` to activity `B`.
2. Change a developer setting using the `DeveloperSettingsFragment`.
3. Navigate back to activity `A`.
4. Open the `FrameLayout` to see current developer settings.

Observed behaviour: although the developer settings have correctly been updated in the `DeveloperSettingsModel`, the UI of activity `A` shows the old developer settings being enabled.

Expected behabiour: the UI of activity `A` should reflect the updated and currently enabled developer settings.

### PR DESCRIPTION
**Pull request by kimar**
Fixes https://github.com/artem-zinnatullin/qualitymatters/issues/200

### CODE REVIEW

File: app/src/debug/java/com/artemzin/qualitymatters/ui/presenters/DeveloperSettingsPresenter.java [hunk 1]
```diff
@@ -23,15 +23,22 @@ public DeveloperSettingsPresenter(@NonNull DeveloperSettingsModelImpl developerS
...
 
-        view.changeGitSha(developerSettingsModel.getGitSha());
-        view.changeBuildDate(developerSettingsModel.getBuildDate());
-        view.changeBuildVersionCode(developerSettingsModel.getBuildVersionCode());
-        view.changeBuildVersionName(developerSettingsModel.getBuildVersionName());
-        view.changeStethoState(developerSettingsModel.isStethoEnabled());
-        view.changeLeakCanaryState(developerSettingsModel.isLeakCanaryEnabled());
-        view.changeTinyDancerState(developerSettingsModel.isTinyDancerEnabled());
-        view.changeHttpLoggingLevel(developerSettingsModel.getHttpLoggingLevel());
+        if (view != null) {
```
Comment (artem-zinnatullin) [inline app/src/debug/java/com/artemzin/qualitymatters/ui/presenters/DeveloperSettingsPresenter.java]: I would actually crash here instead of no-op, we shouldn't call this method when `view == null`

File: app/src/debug/java/com/artemzin/qualitymatters/ui/presenters/DeveloperSettingsPresenter.java [hunk 2]
```diff
@@ -23,15 +23,22 @@ public DeveloperSettingsPresenter(@NonNull DeveloperSettingsModelImpl developerS
     @Override
     public void bindView(@NonNull DeveloperSettingsView view) {
         super.bindView(view);
+        syncDeveloperSettings();
+    }
+
+    public void syncDeveloperSettings() {
```
Comment (artem-zinnatullin) [inline app/src/debug/java/com/artemzin/qualitymatters/ui/presenters/DeveloperSettingsPresenter.java]: Ideally that would be reactive, but ok for now :)

**Comment by artem-zinnatullin** [comment]
Can you please merge latest `master` in your PR branch so CI would work normally?

**Comment by kimar** [comment]
@artem-zinnatullin pulled `master` from upstream, also intentionally crashes on NPE now.

**Comment by artem-zinnatullin** [comment]
@vanniktech PTAL :)

**Comment by artem-zinnatullin** [comment]
Thank you!

**Comment by vanniktech** [comment]
Whops. Totally missed this one. Sorry :/

**Comment by artem-zinnatullin** [comment]
@vanniktech np :)
